# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
    role: master
  name: {{ template "opendistro-es.fullname" . }}-master
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.elasticsearch.master.replicas }}
  template:
    metadata:
      labels:
        role: master
    spec:
      serviceAccountName: {{ template "opendistro-es.elasticsearch.serviceAccountName" . }}
      # Add toleration for not scheduling on dedicated node
      tolerations:
      - key: dedicated
        value: "true"
        effect: NoSchedule
      # Anti-affinity to disallow deploying client and master nodes on the same worker node
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                role: master
      {{- with .Values.elasticsearch.master.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count={{ .Values.elasticsearch.maxMapCount }}
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        env:
        - name: CLUSTER_NAME
          value: {{ .Values.clusterName }}
        - name: NUMBER_OF_MASTERS
          value: {{ .Values.elasticsearch.master.replicas | quote }}
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: HTTP_ENABLE
          value: "true"
    {{- if .Values.elasticsearch.transportKeyPassphrase.enabled}}
        - name: TRANSPORT_KEY_PASSPHRASE
          value: {{ .Values.elasticsearch.keyPassphrase.passPhrase }}
    {{- end }}
    {{- if .Values.elasticsearch.transportKeyPassphrase.enabled}}
        - name: SSL_KEY_PASSPHRASE
          value: {{ .Values.elasticsearch.sslKeyPassphrase.passPhrase }}
    {{- end }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: {{ template "opendistro-es.fullname" . }}-discovery
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: {{ .Values.elasticsearch.master.javaOpts }}
        resources:
{{ toYaml .Values.elasticsearch.master.resources | indent 8 }}
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 10
        # Official Image from Open Distro Team
        image: {{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.imageTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        - containerPort: 9600
          name: metrics
        volumeMounts:
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/logging.yml
          name: config
          subPath: logging.yml
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/log4j2.properties
          name: config
          subPath: log4j2.properties
         {{- if and .Values.elasticsearch.ssl.transport.enabled .Values.elasticsearch.ssl.transport.existingCertSecret }}
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/elk-transport-crt.pem
          name: transport-certs
          subPath: elk-transport-crt.pem
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/elk-transport-key.pem
          name: transport-certs
          subPath: elk-transport-key.pem
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/elk-transport-root-ca.pem
          name: transport-certs
          subPath: elk-transport-root-ca.pem
         {{- end }}
         {{- if and .Values.elasticsearch.ssl.rest.enabled .Values.elasticsearch.ssl.rest.existingCertSecret }}
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/elk-rest-crt.pem
          name: rest-certs
          subPath: elk-rest-crt.pem
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/elk-rest-key.pem
          name: rest-certs
          subPath: elk-rest-key.pem
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/elk-rest-root-ca.pem
          name: rest-certs
          subPath: elk-rest-root-ca.pem
        {{- end }}
        {{- if and .Values.elasticsearch.ssl.admin.enabled .Values.elasticsearch.ssl.admin.existingCertSecret }}
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/admin-crt.pem
          name: admin-certs
          subPath: admin-crt.pem
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/admin-key.pem
          name: admin-certs
          subPath: admin-key.pem
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/admin-root-ca.pem
          name: admin-certs
          subPath: admin-root-ca.pem
       {{- end }}
      {{- if .Values.elasticsearch.securityConfig.enabled }}
      {{- if .Values.elasticsearch.securityConfig.actionGroupsSecret }}
        - mountPath: {{ .Values.elasticsearch.securityConfig.path }}/action_groups.yml
          name: action-groups
          subPath: action_groups.yml
       {{- end }}
       {{- if .Values.elasticsearch.securityConfig.configSecret }}
        - mountPath: {{ .Values.elasticsearch.securityConfig.path }}/config.yml
          name: security-config
          subPath: config.yml
       {{- end }}
       {{- if .Values.elasticsearch.securityConfig.internalUsersSecret }}
        - mountPath: {{ .Values.elasticsearch.securityConfig.path }}/internal_users.yml
          name: internal-users-config
          subPath: internal_users.yml
       {{- end }}
       {{- if .Values.elasticsearch.securityConfig.rolesSecret }}
        - mountPath: {{ .Values.elasticsearch.securityConfig.path }}/roles.yml
          name: roles
          subPath: roles.yml
       {{- end }}
       {{- if .Values.elasticsearch.securityConfig.rolesMappingSecret }}
        - mountPath: {{ .Values.elasticsearch.securityConfig.path }}/roles_mapping.yml
          name: role-mapping
          subPath: roles_mapping.yml
      {{- end }}
      {{- end }}
      volumes:
      - name: config
        secret:
          secretName: elasticsearch-config
      {{- if and .Values.elasticsearch.ssl.transport.enabled .Values.elasticsearch.ssl.transport.existingCertSecret }}
      - name: transport-certs
        secret:
          secretName: {{ .Values.elasticsearch.ssl.transport.existingCertSecret }}
      {{- end }}
      {{- if and .Values.elasticsearch.ssl.rest.enabled .Values.elasticsearch.ssl.rest.existingCertSecret }}
      - name: rest-certs
        secret:
          secretName: {{ .Values.elasticsearch.ssl.rest.existingCertSecret }}
      {{- end }}
      {{- if and .Values.elasticsearch.ssl.admin.enabled .Values.elasticsearch.ssl.admin.existingCertSecret }}
      - name: admin-certs
        secret:
          secretName: {{ .Values.elasticsearch.ssl.admin.existingCertSecret }}
      {{- end }}
      {{- if .Values.elasticsearch.securityConfig.actionGroupsSecret }}
      - name: action-group
        secret:
          secretName: {{ .Values.elasticsearch.securityConfig.actionGroupsSecret }}
      {{- end }}
      {{- if .Values.elasticsearch.securityConfig.configSecret }}
      - name: security-config
        secret:
          secretName: {{ .Values.elasticsearch.securityConfig.configSecret }}
      {{- end }}
      {{- if .Values.elasticsearch.securityConfig.internalUsersSecret }}
      - name: internal-users-config
        secret:
          secretName: {{ .Values.elasticsearch.securityConfig.internalUsersSecret }}
      {{- end }}
      {{- if .Values.elasticsearch.securityConfig.rolesSecret }}
      - name: roles
        secret:
          secretName: {{ .Values.elasticsearch.securityConfig.rolesSecret }}
      {{- end }}
      {{- if .Values.elasticsearch.securityConfig.rolesMappingSecret }}
      - name: role-mapping
        secret:
          secretName: {{ .Values.elasticsearch.securityConfig.rolesMappingSecret }}
      {{- end -}}
