# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
{{- if .Values.elasticsearch.client.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.elasticsearch.client.service.annotations | indent 4 }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
    role: client
  name: {{ template "opendistro-es.fullname" . }}-client-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
    - name: metrics
      port: 9600
  selector:
    role: client
  type: {{ .Values.elasticsearch.client.service.type }}
{{- end }}
