apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
    role: master
  name: {{ template "opendistro-es.fullname" . }}-discovery
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9300
      protocol: TCP
  clusterIP: None
  selector:
    role: master
