{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.kibana.service.annotations | indent 4 }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
  name: {{ template "opendistro-es.fullname" . }}-kibana-svc
spec:
  ports:
  - name: kibana-svc
    port: {{ .Values.kibana.externalPort }}
    targetPort: {{ .Values.kibana.port }}
  selector:
    app: {{ template "opendistro-es.fullname" . }}-kibana
  type: {{ .Values.kibana.service.type }}
{{- end }}
