{{- if and .Values.rbac.enabled .Values.kibana.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
  name: {{ template "opendistro-es.fullname" . }}-kibana-rolebinding
roleRef:
  kind: Role
  name: {{ template "opendistro-es.kibana.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "opendistro-es.kibana.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
