appVersion: 1.0.0
description: 'Opendistro Elasticsearch'
engine: gotpl
kubeVersion: ^1.10.0-0
maintainers:
- email: derek.heldt-werle@viasat.com
- email: kalvin.chau@viasat.com
  name: OpenDistro ES Maintainers
name: opendistro-es
sources:
- https://pages.git.viasat.com/ATG/charts
version: 1.1.0
